### ISSUE TITLE
exchange "request" with "http.min"

### ISSUE THREAD

**Issue by bvdbos** [netactivenl/com.logitech.harmony.hub#3]
Don't know if it's possible in this app but http.min seems to work better then request...
https://athomcommunity.slack.com/archives/developers/p1465328720000123

**Comment by netactivenl** [comment]
Nope, the app uses a library that handles the connections.
Op 7 jun. 2016 22:30 schreef "Bas van den Bosch" notifications@github.com:

Don't know if it's possible in this app but http.min seems to work better
then request...
https://athomcommunity.slack.com/archives/developers/p1465328720000123

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/netactivenl/com.logitech.harmony.hub/issues/3, or mute
the thread
https://github.com/notifications/unsubscribe/AQhFFWiexrzORPgfyWFyBtlGggWh0i_Lks5qJdTrgaJpZM4IwVCj
.
